//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public enum CustomersType : int
{
	Gold_Partner = 1,
	Silver_Partner = 2,
	Registered_Partner = 3,
}
