//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Customer
{
    private FileLogger _myLogger = new FileLogger();
	public void Add()
	{
        try
        {
            //Business call goes here
        }
        catch (Exception err)
        {
            _myLogger.Handle(err.ToString());
        }
	}

}

