//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Customer
{
    private FileLogger _myLogger = new FileLogger();
    private CustomersType _customerType;

    /// <summary>
    /// Reference to the type of customer
    /// </summary>
    public virtual CustomersType CustomerType
    {
        get { return _customerType; }
        set { _customerType = value; }
    }

    public virtual void Add()
    {
        try
        {
            //Business rules goes here.
        }
        catch (Exception err)
        {
            _myLogger.Handle(err.Message);
        }
    }
    public virtual double getDiscount(double TotalSales)
	{
        return TotalSales;
	}

}

