//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Developer : Employee, IDeveloper
{
    IEnumerable<Skill> _skillList;
    public IEnumerable<Skill> DeveloperSkills
    {
        get
        {
            return _skillList;
        }

        set
        {
            _skillList = value;
        }
    }

    public virtual void FillAgenda()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MakePOC()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CodingUnitTest()
	{
		throw new System.NotImplementedException();
	}

	public Developer()
	{
	}

}

