//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class EmailLogger : ILogger
{
	public virtual void Handle(string error)
	{
        Console.WriteLine("I will send this info '{0}' inside the body of Email.", error);
    }

}

