//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee : Person
{
	public virtual object RangeSalary
	{
		get;
		set;
	}

	public virtual object Salary
	{
		get;
		set;
	}

	public Employee()
	{
	}

}

