//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class EvenViewerLogger : ILogger
{
	public virtual void Handle(string error)
	{
        Console.WriteLine("I will write this info '{0}' in Event Viewer", error);
	}

}

