//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class FileLogger
{
	public virtual void Handle(string error)
	{
		throw new System.NotImplementedException();
	}

}

