//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class GoldCustomer : Customer
{
    public override void Add()
    {
        Console.WriteLine("Because I'm Gold Customer I can Add data");
    }
    public override double getDiscount(double TotalSales)
	{
        var sales = base.getDiscount(TotalSales);
        return (sales * 0.30);
    }

}

