//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Person
{
	public virtual object Gender
	{
		get;
		set;
	}

	public virtual int Age
	{
		get;
		set;
	}

	public virtual object Status
	{
		get;
		set;
	}

	public virtual object Identification
	{
		get;
		set;
	}

	public virtual object IdentificationType
	{
		get;
		set;
	}

	public virtual object FirstName
	{
		get;
		set;
	}

	public virtual object LastName
	{
		get;
		set;
	}

	public virtual object CellPhone
	{
		get;
		set;
	}

	/// <summary>
	/// Address where the prototype or employee resides
	/// </summary>
	public virtual string Address
	{
		get;
		set;
	}

	public Person()
	{
	}

}

