//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

public class PlatiniumCustomer : Customer, IManageableV1
{
	public virtual void Read()
	{
        Console.WriteLine("Because I'm Platinium Customer I can read data");
	}

	public override void Add()
	{
        Console.WriteLine("Because I'm Platinium Customer I can Add data also");
    }

    public override double getDiscount(double TotalSales)
    {
        var sales = base.getDiscount(TotalSales);
        return (sales * 0.45);
    }

}

