//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

public class PlatiniumCustomer : Customer, IManageableV1
{
    private ILogger _myLogger;
    public PlatiniumCustomer(ILogger log) : base(log)
    {
        _myLogger = log;
    }

    public virtual void Read()
	{
        Console.WriteLine("Because I'm Platinium Customer I can read data");
	}

	public override void Add()
	{
        try
        {
            Console.WriteLine("Because I'm Platinium Customer I can Add data also");
            throw new ApplicationException("Proof concept");
        }
        catch (Exception err)
        {
            _myLogger.Handle(err.Message);
        }
    }

    public override double getDiscount(double TotalSales)
    {
        var sales = base.getDiscount(TotalSales);
        return (sales * 0.45);
    }

}

