//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class QADeveloper : Employee, ITester
{
	public virtual void DesignTestCases()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ExecuteTestCases()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RegisterBuggsFound()
	{
		throw new System.NotImplementedException();
	}

	public QADeveloper()
	{
	}

}

