//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class RegisteredCustomer : Customer
{
    private ILogger _myLogger;
    public RegisteredCustomer(ILogger log) : base(log)
    {
        _myLogger = log;
    }

    public override void Add()
    {
        try
        {
            Console.WriteLine("Because I'm Registered Customer I can Add data");
            throw new ApplicationException("Proof concept");
        }
        catch (Exception err)
        {
            _myLogger.Handle(err.Message);
        }
    }
    /// <summary>
    /// Get discount applied to total Sales
    /// </summary>
    public override double getDiscount(double TotalSales)
	{
        var sales = base.getDiscount(TotalSales);
        return (sales * 0.05);
    }
}

