//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SilverCustomer : Customer
{
    private ILogger _myLogger;
    public SilverCustomer(ILogger log) : base(log)
    {
        _myLogger = log;
    }

    public override void Add()
    {
        try
        {
            Console.WriteLine("Because I'm Silver Customer I can Add data");
            throw new ApplicationException("Proof concept");
        }
        catch (Exception err)
        {
            _myLogger.Handle(err.Message);
        }
    }
    public override double getDiscount(double TotalSales)
	{
        var sales = base.getDiscount(TotalSales);
        return (sales * 0.15);
	}

}

